# Generated by Django 4.2.30 on 2026-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('año', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
