# Generated by Django 6.1.1 on 2026-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Ejecucion', 'En ejecución'), ('Progreso', 'En progreso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], max_length=50),
        ),
    ]
