# Generated by Django 6.1.1 on 2026-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_monto_proyecto_num_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='monto_final',
            field=models.IntegerField(default=0),
        ),
    ]
